### PR TITLE
Minor change: fixed link to issues in Introduction

### PR DESCRIPTION
**Pull request by sypets**

### CODE REVIEW

**Comment by marble** [comment]
Hi, good to see you here. Send more!

**Comment by sypets** [comment]
Thanks! Will do, unless I don't find anything else. That would be even better!

**Comment by marble** [comment]
Nope! No hope on this! There is lots to find. But, on the other hand: We are very good already!

**Comment by sypets** [comment]
Yes! And it's not easy to document a rapidly moving target because the core developers are so hard-working. 

CU

**Pull request merged**
